web/sayur-mayur/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});
// Route::get('/dashboard', 'Backend\DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('master')->group(function () {
        Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
        Route::resource('user', 'Backend\AdminController');
        Route::resource('courrier', 'Backend\CourrierController');
        Route::resource('supplier', 'Backend\SupplierController');
        Route::resource('product', 'Backend\ProductController');
        Route::resource('recipe', 'Backend\RecipeController');
        Route::resource('ingredients', 'Backend\IngredientController');
    });
});

require __DIR__.'/auth.php';

web/sayur-mayur/app/Http/Controllers/Backend/CourrierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Courrier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CourrierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Kurir';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Kurir';
        $this->param['data'] = Courrier::all();
        $this->param['top_button'] = route('courrier.create');

        return view('backend.courrier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Kurir';
        $this->param['top_button'] = route('courrier.index');
        $courrierCode = null;
        $courrier = Courrier::orderBy('courrier_code', 'DESC')->get();
        
        if($courrier->count() > 0){
            $courrierCode = $courrier[0]->courrier_code;

            $lastIncrement = substr($courrierCode, 2);

            $courrierCode = str_pad($lastIncrement + 1, 3, 0, STR_PAD_LEFT);
            $courrierCode = 'CC'.$courrierCode;
            
        }
        else{
            $courrierCode = "CC001";
        }
        $this->param['courrier_code'] = $courrierCode;

        return view('backend.courrier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'courrier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'gender' => 'required',
                'phone' => 'required|min:11|max:13|unique:courrier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'courrier_code' => 'Kode Kurir',
                'nama_lengkap' => 'Nama lengkap',
                'gender' => 'Jenis kelamin',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newCourrier = new Courrier;
            $newCourrier->courrier_code = $request->get('courrier_code');
            $newCourrier->name = $request->get('nama_lengkap');
            $newCourrier->gender = $request->get('gender');
            $newCourrier->phone = $request->get('phone');
            
            $newCourrier->save();
            return redirect('master/courrier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($courrierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('courrier.index');
            $this->param['courrier'] = Courrier::where('courrier_code', $courrierCode)->first();
            
            return view('backend.courrier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $courrierCode)
    {
        try{
            $courrier = Courrier::where('courrier_code', $courrierCode)->first();

            $isUnique = $courrier->phone == $request->get('phone') ? '' : '|unique:courrier,phone';
            $this->validate($request, 
                [
                    'courrier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'gender' => 'required',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'courrier_code' => 'Kode Kurir',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('courrier')->where('courrier_code', $courrierCode)->update([
                "courrier_code" => $request->get('courrier_code'),
                "name" => $request->get('nama_lengkap'),
                "gender" => $request->get('gender'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/courrier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($courrierCode)
    {
        try{
            DB::delete('delete from courrier where courrier_code = ?', [$courrierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard');
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/SupplierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SupplierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Suplier';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Suplier';
        $this->param['data'] = Supplier::all();
        $this->param['top_button'] = route('supplier.create');

        return view('backend.supplier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Suplier';
        $this->param['top_button'] = route('supplier.index');
        $supplierCode = null;
        $supplier = Supplier::orderBy('supplier_code', 'DESC')->get();
    
        if($supplier->count() > 0){
            $supplierCode = $supplier[0]->supplier_code;

            $lastIncreament = substr($supplierCode, 2);

            $supplierCode = str_pad($lastIncreament + 1, 3, 0, STR_PAD_LEFT);
            $supplierCode = 'SC'.$supplierCode;
            
        }
        else{
            $supplierCode = "SC001";
        }
        $this->param['supplier_code'] = $supplierCode;

        return view('backend.supplier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'supplier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'address' => 'required|min:8',
                'phone' => 'required|min:11|max:13|unique:supplier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'address.min' => 'Harap masukkan dengan benar.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'supplier_code' => 'Kode Suplier',
                'nama_lengkap' => 'Nama lengkap',
                'address' => 'Alamat',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newSupplier = new Supplier;
            $newSupplier->supplier_code = $request->get('supplier_code');
            $newSupplier->name = $request->get('nama_lengkap');
            $newSupplier->address = $request->get('address');
            $newSupplier->phone = $request->get('phone');
            
            $newSupplier->save();
            return redirect('master/supplier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($supplierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('supplier.index');
            $this->param['supplier'] = Supplier::where('supplier_code', $supplierCode)->first();
            
            return view('backend.supplier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $supplierCode)
    {
        try{
            $supplier = Supplier::where('supplier_code', $supplierCode)->first();

            $isUnique = $supplier->phone == $request->get('phone') ? '' : '|unique:supplier,phone';
            $this->validate($request, 
                [
                    'supplier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'address' => 'required|min:8',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'address.min' => 'Harap masukkan dengan benar.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'supplier_code' => 'Kode Suplier',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('supplier')->where('supplier_code', $supplierCode)->update([
                "supplier_code" => $request->get('supplier_code'),
                "name" => $request->get('nama_lengkap'),
                "address" => $request->get('address'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/supplier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($supplierCode)
    {
        try{
            DB::delete('delete from supplier where supplier_code = ?', [$supplierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

web/sayur-mayur/resources/views/backend/layout/master.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template">
    <meta name="description"
        content="Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
    <meta name="robots" content="noindex,nofollow">
    <title>{{ ucwords(Request::segment(2)) }} - Sayur Mayur</title>
    <link rel="canonical" href="https://www.wrappixel.com/templates/ample-admin-lite/" />
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="plugins/images/favicon.png">
    <!-- Custom CSS -->
   
    <link href="{{ asset('backend/css/style.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    {{-- <link href="{{ asset('backend/css/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/css/icons/themify-icons/themify-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/css/icons/material-design-iconic-font/css/materialdesignicons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/css/icons/weather-icons/css/weather-icons.min.css') }}" rel="stylesheet"> --}}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        @include('backend.layout.topbar')
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar scroll-->
            @include('backend.layout.sidebar')
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        @yield('content')
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ asset('backend/plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{ asset('backend/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('backend/js/app-style-switcher.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('backend/js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('backend/js/sidebarmenu.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('backend/js/custom.js') }}"></script>
    <!-- Data Table -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function() {
            $('#data_table').DataTable();
            $('.showDetailData').click(function (e) { 
                let imageSrc = $(this).data('image');
                $('.modal-body #showDetail').attr('src', imageSrc);
            });
        });

    </script>
</body>

</html>

web/sayur-mayur/resources/views/backend/layout/sidebar.blade.php
<div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <!-- User Profile-->
                <li class="sidebar-item pt-2">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'dashboard' ? 'active' : '' }}" href="{{ route('dashboard') }}"
                        aria-expanded="false">
                        <i class="fas fa-tachometer-alt" aria-hidden="true"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'user' ? 'active' : '' }}" href="{{ route('user.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span class="hide-menu">User</span>
                    </a>
                </li>
                {{-- <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'courrier' ? 'active' : '' }}" href="{{ route('courrier.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-truck" aria-hidden="true"></i>
                        <span class="hide-menu">Kurir</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'supplier' ? 'active' : '' }}" href="{{ route('supplier.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-people-carry" aria-hidden="true"></i>
                        <span class="hide-menu">Suplier</span>
                    </a>
                </li> --}}
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'product' ? 'active' : '' }}" href="{{ route('product.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-box-open" aria-hidden="true"></i>
                        <span class="hide-menu">Produk</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'recipe' ? 'active' : '' }}" href="{{ route('recipe.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-book" aria-hidden="true"></i>
                        <span class="hide-menu">Resep</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link {{ Request::segment(2) == 'ingredients' ? 'active' : '' }}" href="{{ route('ingredients.index') }}"
                        aria-expanded="false">
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
                        <span class="hide-menu">Bahan-bahan</span>
                    </a>
                </li>
                <li class="text-center p-20 upgrade-btn">
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf
                        <button class="btn d-grid btn-danger text-white w-100">
                            Logout
                        </button>
                    </form>
                </li>
            </ul>

        </nav>
        <!-- End Sidebar navigation -->
    </div>

web/sayur-mayur/resources/views/backend/layout/topbar.blade.php
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="dashboard.html">
                <!-- Logo icon -->
                <b class="logo-icon">
                    <!-- Dark Logo icon -->
                    <img src="plugins/images/logo-icon.png" alt="homepage" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="plugins/images/logo-text.png" alt="homepage" />
                </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav d-none d-md-block d-lg-none">
                <li class="nav-item">
                    <a class="nav-toggler nav-link waves-effect waves-light text-white"
                        href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav ms-auto d-flex align-items-center">

                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                {{-- <li class=" in">
                    <form role="search" class="app-search d-none d-md-block me-3">
                        <input type="text" placeholder="Search..." class="form-control mt-0">
                        <a href="" class="active">
                            <i class="fa fa-search"></i>
                        </a>
                    </form>
                </li> --}}
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li>
                    <a class="profile-pic" href="#">
                        <i class="fas fa-user"></i>
                        <span class="ml-2">{{ Auth::user()->name }}</span>
                        {{-- <img src="plugins/images/users/varun.jpg" alt="user-img" width="36"
                            class="img-circle"><span class="text-white font-medium">Steave</span></a> --}}
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>