web/sayur-mayur/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});
// Route::get('/dashboard', 'Backend\DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('master')->group(function () {
        Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
        Route::resource('user', 'Backend\AdminController');
        Route::resource('courrier', 'Backend\CourrierController');
        Route::resource('supplier', 'Backend\SupplierController');
        Route::resource('product', 'Backend\ProductController');
        Route::resource('recipe', 'Backend\RecipeController');
        Route::resource('ingredients', 'Backend\IngredientController');
    });
});

require __DIR__.'/auth.php';

web/sayur-mayur/app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use HasFactory;
    protected $table = 'recipe';
}

web/sayur-mayur/app/Http/Controllers/API/RecipeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Ingredients;
use App\Models\Recipe;
use Illuminate\Http\Request;

class RecipeController extends Controller
{
    public function allRecipe()
    {
        $data = null;
        $status = null;
        $msg = null;
        try {
            $data = Recipe::orderBy('name', 'ASC')->get();
            $status = 200;
        }
        catch (\Exception $e) {
            $data = 'error';
            $status = 400;
            $msg = $e->getMessage();
        }
        catch(\Illuminate\Database\QueryException $e) {
            $data = 'database error';
            $status = 400;
            $msg = $e->getMessage();
        }
        finally{
            $result = [
                'status' => $status,
                'message' => $msg,
                'data' => $data,
            ];
            return response($result, $status);
        }
    }

    public function ingredients($recipe_code)
    {
        $data = null;
        $status = null;
        $msg = null;
        try {
            $data = Ingredients::select('ingredients.product_code', 'ingredients.dose', 'products.name', 'products.cover')
                                ->join('products', 'products.product_code', 'ingredients.product_code')
                                ->where('ingredients.recipe_code', $recipe_code)
                                ->orderBy('products.name', 'ASC')
                                ->get();

            $status = 200;
        }
        catch (\Exception $e) {
            $data = 'error';
            $status = 400;
            $msg = $e->getMessage();
        }
        catch(\Illuminate\Database\QueryException $e) {
            $data = 'database error';
            $status = 400;
            $msg = $e->getMessage();
        }
        finally{
            $result = [
                'status' => $status,
                'message' => $msg,
                'data' => $data,
            ];
            return response($result, $status);
        }
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/CourrierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Courrier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CourrierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Kurir';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Kurir';
        $this->param['data'] = Courrier::all();
        $this->param['top_button'] = route('courrier.create');

        return view('backend.courrier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Kurir';
        $this->param['top_button'] = route('courrier.index');
        $courrierCode = null;
        $courrier = Courrier::orderBy('courrier_code', 'DESC')->get();
        
        if($courrier->count() > 0){
            $courrierCode = $courrier[0]->courrier_code;

            $lastIncrement = substr($courrierCode, 2);

            $courrierCode = str_pad($lastIncrement + 1, 3, 0, STR_PAD_LEFT);
            $courrierCode = 'CC'.$courrierCode;
            
        }
        else{
            $courrierCode = "CC001";
        }
        $this->param['courrier_code'] = $courrierCode;

        return view('backend.courrier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'courrier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'gender' => 'required',
                'phone' => 'required|min:11|max:13|unique:courrier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'courrier_code' => 'Kode Kurir',
                'nama_lengkap' => 'Nama lengkap',
                'gender' => 'Jenis kelamin',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newCourrier = new Courrier;
            $newCourrier->courrier_code = $request->get('courrier_code');
            $newCourrier->name = $request->get('nama_lengkap');
            $newCourrier->gender = $request->get('gender');
            $newCourrier->phone = $request->get('phone');
            
            $newCourrier->save();
            return redirect('master/courrier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($courrierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('courrier.index');
            $this->param['courrier'] = Courrier::where('courrier_code', $courrierCode)->first();
            
            return view('backend.courrier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $courrierCode)
    {
        try{
            $courrier = Courrier::where('courrier_code', $courrierCode)->first();

            $isUnique = $courrier->phone == $request->get('phone') ? '' : '|unique:courrier,phone';
            $this->validate($request, 
                [
                    'courrier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'gender' => 'required',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'courrier_code' => 'Kode Kurir',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('courrier')->where('courrier_code', $courrierCode)->update([
                "courrier_code" => $request->get('courrier_code'),
                "name" => $request->get('nama_lengkap'),
                "gender" => $request->get('gender'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/courrier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($courrierCode)
    {
        try{
            DB::delete('delete from courrier where courrier_code = ?', [$courrierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard');
    }
}

web/sayur-mayur/resources/views/backend/recipe/create-detail.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Bahan-bahan</td>
            <td>Takaran</td>
            <td>Aksi</td>
        </tr>
    </thead>
    <tbody>
        <tr id="field1">
            <input type="hidden" id="count" value="1" />
            <td>
                <select name="product_code[]" id="product_code[]" class="form-control">
                    <option value="">Pilih bahan</option>
                    @foreach ($product as $product_item)
                        <option value="{{ $product_item->product_code }}">{{ $product_item->product_code }} - {{ $product_item->name }}</option>
                    @endforeach
                </select>
            </td>
            <td>
                <input type="number" name="dose[]" id="dose[]" class="form-control" placeholder="Masukkan takaran disini">
            </td>
            <td>
                <button type="button" class="btn btn-danger ml-4 btn-delete-field" id="btn-delete-field1" style="display: none;"><span class="fa fa-minus"></span></button>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2"></td>
            <td class="text-center">
                <button type="button" class="btn btn-primary btn-add-more1" id="btn_add_item">Tambah</button>
            </td>
        </tr>
    </tfoot>
</table>

{{-- <div class="row mb-2 field">
    <div class="col">
        <select name="product_code[]" id="product_code[]" class="form-control">
            <option value="">Pilih bahan</option>
            @foreach ($product as $product_item)
                <option value="{{ $product_item->product_code }}">{{ $product_item->product_code }} - {{ $product_item->name }}</option>
            @endforeach
        </select>
    </div>
    <div class="col">
        <input autocomplete="off" class="input form-control" id="field1" name="prof1" type="text" placeholder="Type something" data-items="8"/>
    </div>
    <div class="col">
        <button id="b1" class="btn add-more" type="button">+</button>
    </div>
</div> --}}

web/sayur-mayur/resources/views/backend/recipe/create.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>&nbsp;{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white">
                        Lihat Data
                    </a>
                    <form class="mt-4" action="{{ route('recipe.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="formResep">Kode Resep</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formResep" name="recipe_code" value="{{ $recipe_code }}" placeholder="ex : RC001" value="{{ old('recipe_code') }}" readonly>
                                    @error('recipe_code')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formNama">Nama Resep</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formNama" name="recipe_name" placeholder="ex : Pecel" value="{{ old('recipe_name') }}">
                                    @error('recipe_name')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formCover">Sampul</label>
                                    <input type="file" name="cover" id="formCover" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formStock">Stok</label><span class="text-danger">*</span>
                                    <input type="number" class="form-control" id="formStock" name="stock" placeholder="ex : 20" value="{{ old('stock') }}">
                                    @error('stock')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formLaba">Laba(Rp)</label><span class="text-danger">*</span>
                                    <input type="number" class="form-control" id="formLaba" name="laba" placeholder="ex : 7,000.00" value="{{ old('laba') }}">
                                    @error('laba')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        {{-- @include('backend.recipe.create-detail') --}}
                        <div class="form-inline">
                            <input type="submit" value="Simpan" class="btn btn-success mr-2">
                            <input type="reset" value="Batal" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
@endsection

web/sayur-mayur/resources/views/backend/recipe/index.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Sukses!</strong>&nbsp;{{ session('status') }}
                    </div>
                    @endif
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white mb-3">
                        Tambah
                    </a>
                    <table class="table table-xl-responsive mt-4" id="data_table">
                        <thead>
                            <th class="text-center">Kode Resep</th>
                            <th class="text-center">Nama</th>
                            <th class="text-center">Stok</th>
                            <th class="text-center">Harga</th>
                            <th class="text-center">Aksi</th>
                        </thead>
                        <tbody>
                            @forelse ($data as $item)
                            <tr>
                                <td class="text-center pt-4">{{ $item->recipe_code }}</td>
                                <td>
                                    <a style="cursor: pointer;" data-toggle="modal" class="showDetailData" data-target=".modal-show-detail" data-image="{{ url(''.$item->cover) }}">
                                        <img src="{{ url(''.$item->cover) }}" class="rounded mr-4" alt="{{ $item->name }}" width="80" height="80">
                                    </a>
                                    {{ $item->name }}
                                </td>
                                <td class="text-center">{{ $item->stock }}</td>
                                <td class="text-right">Rp{{ number_format($item->price, 2, ',', '.') }}</td>
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <div class="form-inline p-0">
                                            <a href="{{ route('recipe.show', $item->recipe_code) }}" class="btn btn-primary mr-2" title="Edit" data-toggle="tooltip"> <span class="fa fa-eye"></span> </a>
                                            <a href="{{ route('recipe.edit', $item->recipe_code) }}" class="btn btn-success mr-2" title="Edit" data-toggle="tooltip"> <span class="fa fa-pen"></span> </a>
                                            <form action="{{ route('recipe.destroy', $item->recipe_code) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <button type="button" class="btn btn-danger" title="Hapus" data-toggle="tooltip" onclick="confirm('{{ __("Apakah anda yakin ingin menghapus?") }}') ? this.parentElement.submit() : ''">
                                                    <span class="fa fa-minus-circle"></span>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @empty
                                
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<div class="modal modal-show-detail">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          {{-- <h6 class="modal-title">Detail Data</h6> --}}
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body text-center">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <img alt="" id="showDetail" width="100%">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection