web/sayur-mayur/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});
// Route::get('/dashboard', 'Backend\DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('master')->group(function () {
        Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
        Route::resource('user', 'Backend\AdminController');
        Route::resource('courrier', 'Backend\CourrierController');
        Route::resource('supplier', 'Backend\SupplierController');
        Route::resource('product', 'Backend\ProductController');
        Route::resource('recipe', 'Backend\RecipeController');
        Route::resource('ingredients', 'Backend\IngredientController');
    });
});

require __DIR__.'/auth.php';

web/sayur-mayur/app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $table = 'supplier';
}

web/sayur-mayur/app/Http/Controllers/Backend/CourrierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Courrier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CourrierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Kurir';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Kurir';
        $this->param['data'] = Courrier::all();
        $this->param['top_button'] = route('courrier.create');

        return view('backend.courrier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Kurir';
        $this->param['top_button'] = route('courrier.index');
        $courrierCode = null;
        $courrier = Courrier::orderBy('courrier_code', 'DESC')->get();
        
        if($courrier->count() > 0){
            $courrierCode = $courrier[0]->courrier_code;

            $lastIncrement = substr($courrierCode, 2);

            $courrierCode = str_pad($lastIncrement + 1, 3, 0, STR_PAD_LEFT);
            $courrierCode = 'CC'.$courrierCode;
            
        }
        else{
            $courrierCode = "CC001";
        }
        $this->param['courrier_code'] = $courrierCode;

        return view('backend.courrier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'courrier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'gender' => 'required',
                'phone' => 'required|min:11|max:13|unique:courrier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'courrier_code' => 'Kode Kurir',
                'nama_lengkap' => 'Nama lengkap',
                'gender' => 'Jenis kelamin',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newCourrier = new Courrier;
            $newCourrier->courrier_code = $request->get('courrier_code');
            $newCourrier->name = $request->get('nama_lengkap');
            $newCourrier->gender = $request->get('gender');
            $newCourrier->phone = $request->get('phone');
            
            $newCourrier->save();
            return redirect('master/courrier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($courrierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('courrier.index');
            $this->param['courrier'] = Courrier::where('courrier_code', $courrierCode)->first();
            
            return view('backend.courrier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $courrierCode)
    {
        try{
            $courrier = Courrier::where('courrier_code', $courrierCode)->first();

            $isUnique = $courrier->phone == $request->get('phone') ? '' : '|unique:courrier,phone';
            $this->validate($request, 
                [
                    'courrier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'gender' => 'required',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'courrier_code' => 'Kode Kurir',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('courrier')->where('courrier_code', $courrierCode)->update([
                "courrier_code" => $request->get('courrier_code'),
                "name" => $request->get('nama_lengkap'),
                "gender" => $request->get('gender'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/courrier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($courrierCode)
    {
        try{
            DB::delete('delete from courrier where courrier_code = ?', [$courrierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard');
    }
}

web/sayur-mayur/app/Http/Controllers/Backend/SupplierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SupplierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Suplier';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Suplier';
        $this->param['data'] = Supplier::all();
        $this->param['top_button'] = route('supplier.create');

        return view('backend.supplier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Suplier';
        $this->param['top_button'] = route('supplier.index');
        $supplierCode = null;
        $supplier = Supplier::orderBy('supplier_code', 'DESC')->get();
    
        if($supplier->count() > 0){
            $supplierCode = $supplier[0]->supplier_code;

            $lastIncreament = substr($supplierCode, 2);

            $supplierCode = str_pad($lastIncreament + 1, 3, 0, STR_PAD_LEFT);
            $supplierCode = 'SC'.$supplierCode;
            
        }
        else{
            $supplierCode = "SC001";
        }
        $this->param['supplier_code'] = $supplierCode;

        return view('backend.supplier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'supplier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'address' => 'required|min:8',
                'phone' => 'required|min:11|max:13|unique:supplier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'address.min' => 'Harap masukkan dengan benar.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'supplier_code' => 'Kode Suplier',
                'nama_lengkap' => 'Nama lengkap',
                'address' => 'Alamat',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newSupplier = new Supplier;
            $newSupplier->supplier_code = $request->get('supplier_code');
            $newSupplier->name = $request->get('nama_lengkap');
            $newSupplier->address = $request->get('address');
            $newSupplier->phone = $request->get('phone');
            
            $newSupplier->save();
            return redirect('master/supplier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($supplierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('supplier.index');
            $this->param['supplier'] = Supplier::where('supplier_code', $supplierCode)->first();
            
            return view('backend.supplier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $supplierCode)
    {
        try{
            $supplier = Supplier::where('supplier_code', $supplierCode)->first();

            $isUnique = $supplier->phone == $request->get('phone') ? '' : '|unique:supplier,phone';
            $this->validate($request, 
                [
                    'supplier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'address' => 'required|min:8',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'address.min' => 'Harap masukkan dengan benar.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'supplier_code' => 'Kode Suplier',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('supplier')->where('supplier_code', $supplierCode)->update([
                "supplier_code" => $request->get('supplier_code'),
                "name" => $request->get('nama_lengkap'),
                "address" => $request->get('address'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/supplier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($supplierCode)
    {
        try{
            DB::delete('delete from supplier where supplier_code = ?', [$supplierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

web/sayur-mayur/resources/views/backend/supplier/create.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>&nbsp;{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white">
                        Lihat Data
                    </a>
                    <form class="mt-4" action="{{ route('supplier.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formSupplier">Kode Suplier</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formSupplier" name="supplier_code" value="{{ $supplier_code }}" placeholder="ex : SC001" value="{{ old('supplier_code') }}" readonly>
                                    @error('supplier_code')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formNama">Nama Lengkap</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formNama" name="nama_lengkap" placeholder="ex : Abdul Hadi" value="{{ old('nama_lengkap') }}">
                                    @error('nama_lengkap')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formAddress">Alamat</label><span class="text-danger">*</span>
                                    <textarea name="address" id="formAddress" class="form-control" cols="30" rows="3">{{ old('address') }}</textarea>
                                    @error('address')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formPhone">No. Hp</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formPhone" name="phone" placeholder="ex : 08145645xxxx" value="{{ old('phone') }}">
                                    @error('phone')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <input type="submit" value="Simpan" class="btn btn-success mr-2">
                            <input type="reset" value="Batal" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
@endsection

web/sayur-mayur/resources/views/backend/supplier/edit.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>&nbsp;{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white">
                        Lihat Data
                    </a>
                    <form class="mt-4" action="{{ route('supplier.update', $supplier->supplier_code) }}" method="POST">
                        @csrf
                        @method("PUT")
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formSupplier">Kode Suplier</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formSupplier" name="supplier_code" value="{{ $supplier->supplier_code }}" placeholder="ex : SC001" readonly>
                                    @error('supplier_code')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formNama">Nama Lengkap</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formNama" name="nama_lengkap" placeholder="ex : Abdul Hadi" value="{{ old('nama_lengkap', $supplier->name) }}">
                                    @error('nama_lengkap')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="formAddress">Alamat</label><span class="text-danger">*</span>
                                    <textarea name="address" id="formAddress" class="form-control" cols="30" rows="3">{{ old('address', $supplier->address) }}</textarea>
                                    @error('address')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="formPhone">No. Hp</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formPhone" name="phone" placeholder="ex : 08145645xxxx" value="{{ old('phone', $supplier->phone) }}">
                                    @error('phone')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <input type="submit" value="Simpan" class="btn btn-success mr-2">
                            <input type="reset" value="Batal" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
@endsection